seed: 42
notes: "baseline plus ultra experiment"

data:
  sqlite_path: data/market.db
  symbol_universe: []
  indicators: {}
  resample_rule: null
  tz_convert: null
  feature_set: null
  target_columns: [close]
  window_size: 512
  horizon: 5
  stride: 8
  normalise: true
  val_fraction: 0.2

model:
  feature_dim: 128
  model_dim: 768
  depth: 16
  heads: 12
  dropout: 0.1
  conv_kernel_size: 7
  conv_dilations: [1, 2, 4, 8, 16, 32, 64]
  horizon: 5
  output_dim: 1
  architecture: omni_mixture
  ff_mult: 4
  ssm_state_dim: 256
  ssm_kernel_size: 16
  coarse_factor: 4
  cross_every: 2
  max_seq_len: 4096

optimizer:
  lr: 0.0002
  weight_decay: 0.01
  betas: [0.9, 0.95]

trainer:
  batch_size: 128
  num_workers: 8
  max_epochs: 150
  gradient_clip_val: 1.0
  accumulate_grad_batches: 2
  accelerator: gpu
  devices: null
  precision: bf16-mixed
  log_every_n_steps: 50
  checkpoint_dir: checkpoints/default
  monitor_metric: val/loss
  monitor_mode: min
  save_top_k: 1

