seed: 42
notes: "baseline plus ultra experiment"

data:
  sqlite_path: data/market.db
  symbol_universe: []
  indicators: {}
  alternative_data: []
  resample_rule: null
  tz_convert: null
  feature_set: null
  target_columns: [close]
  window_size: 512
  horizon: 5
  stride: 8
  normalise: true
  val_fraction: 0.2
  curriculum:
    repeat_final: true
    stages:
      - start_epoch: 0
        window_size: 256
        horizon: 3
        stride: 4
        normalise: true
      - start_epoch: 12
        window_size: 384
        horizon: 4
        stride: 6
      - start_epoch: 24
        window_size: 512
        horizon: 5
        stride: 8

model:
  feature_dim: 128
  model_dim: 768
  depth: 16
  heads: 12
  dropout: 0.1
  conv_kernel_size: 7
  conv_dilations: [1, 2, 4, 8, 16, 32, 64]
  horizon: 5
  output_dim: 1
  architecture: omni_mixture
  ff_mult: 4
  ssm_state_dim: 256
  ssm_kernel_size: 16
  coarse_factor: 4
  cross_every: 2
  max_seq_len: 4096
  calibration:
    enabled: false
    quantiles: [0.05, 0.5, 0.95]
    temperature: 1.0
    min_concentration: 0.01
  scale_factors: [1, 4, 16]
  scale_depth: null
  fusion_heads: 4
  market_state:
    enabled: true
    embedding_dim: 16
    dropout: 0.05
    include: []

optimizer:
  lr: 0.0002
  weight_decay: 0.01
  betas: [0.9, 0.95]

trainer:
  batch_size: 128
  num_workers: 8
  max_epochs: 150
  gradient_clip_val: 1.0
  accumulate_grad_batches: 2
  accelerator: gpu
  devices: null
  precision: bf16-mixed
  log_every_n_steps: 50
  checkpoint_dir: checkpoints/default
  monitor_metric: val/loss
  monitor_mode: min
  save_top_k: 1

diagnostics:
  enabled: true
  log_interval: 50
  profile: false
  gradient_noise_threshold: 4.0
  calibration_bias_threshold: 0.05
  calibration_error_threshold: 0.15

wandb_project: null
wandb_entity: null
wandb_run_name: null
wandb_tags: []
wandb_offline: false

