experiment:
  seed: 42

data:
  database_path: data/market.db
  indicators:
    - rsi
    - macd
    - bbands_width
  asset_universe: []

model:
  input_size: 128
  d_model: 512
  depth: 16
  n_heads: 8
  dilation_rates: [1, 2, 4, 8, 16]
  dropout: 0.2
  forecast_horizon: 5
  output_size: 3

optimizer:
  lr: 0.0003
  weight_decay: 0.0001
  warmup_steps: 2000

training:
  batch_size: 256
  num_epochs: 100
  gradient_clip_val: 1.0
  mixed_precision: true
  checkpoint_dir: checkpoints/default
