seed: 42
notes: "consumer gpu friendly trading config"

data:
  sqlite_path: data/market.db
  symbol_universe: []
  indicators: {}
  alternative_data: []
  resample_rule: null
  tz_convert: null
  feature_set: null
  target_columns: [close]
  window_size: 256
  horizon: 5
  stride: 4
  normalise: true
  val_fraction: 0.2
  curriculum:
    repeat_final: true
    stages:
      - start_epoch: 0
        window_size: 192
        horizon: 3
        stride: 3
        normalise: true
      - start_epoch: 10
        window_size: 256
        horizon: 4
        stride: 4
      - start_epoch: 20
        window_size: 320
        horizon: 5
        stride: 4

model:
  feature_dim: 128
  model_dim: 512
  depth: 12
  heads: 8
  dropout: 0.1
  conv_kernel_size: 7
  conv_dilations: [1, 2, 4, 8, 16, 32]
  horizon: 5
  output_dim: 1
  architecture: omni_mixture
  ff_mult: 4
  ssm_state_dim: 192
  ssm_kernel_size: 12
  coarse_factor: 4
  cross_every: 2
  max_seq_len: 4096
  gradient_checkpointing: true

optimizer:
  lr: 0.0002
  weight_decay: 0.01
  betas: [0.9, 0.95]

trainer:
  batch_size: 24
  num_workers: 4
  persistent_workers: false
  max_epochs: 100
  gradient_clip_val: 1.0
  accumulate_grad_batches: 1
  accelerator: gpu
  devices: null
  precision: bf16-mixed
  matmul_precision: high
  log_every_n_steps: 20
  checkpoint_dir: checkpoints/default_desktop
  monitor_metric: val/loss
  monitor_mode: min
  save_top_k: 1
  num_sanity_val_steps: 0
  limit_train_batches: 1.0
  limit_val_batches: 0.5

diagnostics:
  enabled: true
  log_interval: 20
  profile: true
  gradient_noise_threshold: 4.5
  calibration_bias_threshold: 0.06
  calibration_error_threshold: 0.18

wandb_project: null
wandb_entity: null
wandb_run_name: null
wandb_tags: []
wandb_offline: false
