seed: 42
notes: "mvp cpu-friendly training config"

data:
  sqlite_path: data/plus_ultra_fixture.db
  symbol_universe: []
  indicators: {}
  alternative_data: []
  resample_rule: null
  tz_convert: null
  feature_set: null
  target_columns: [close]
  window_size: 64
  horizon: 1
  stride: 8
  normalise: true
  val_fraction: 0.2
  curriculum:
    repeat_final: true
    stages:
      - start_epoch: 0
        window_size: 48
        horizon: 1
        stride: 6
        normalise: true
      - start_epoch: 2
        window_size: 64
        horizon: 1
        stride: 8

model:
  feature_dim: 27
  model_dim: 128
  depth: 2
  heads: 4
  dropout: 0.1
  conv_kernel_size: 3
  conv_dilations: [1, 2, 4]
  horizon: 1
  output_dim: 1
  architecture: omni_mixture
  ff_mult: 2
  ssm_state_dim: 64
  ssm_kernel_size: 8
  coarse_factor: 2
  cross_every: 1
  max_seq_len: 512
  gradient_checkpointing: false
  calibration:
    enabled: false
    quantiles: [0.05, 0.5, 0.95]
    temperature: 1.0
    min_concentration: 0.01
  market_state:
    enabled: false
    embedding_dim: 8
    dropout: 0.0
    include: []

optimizer:
  lr: 0.001
  weight_decay: 0.0
  betas: [0.9, 0.99]

trainer:
  batch_size: 16
  num_workers: 0
  max_epochs: 3
  gradient_clip_val: 1.0
  accumulate_grad_batches: 1
  accelerator: cpu
  devices: 1
  precision: 32
  log_every_n_steps: 10
  checkpoint_dir: checkpoints/mvp_quickstart
  monitor_metric: val/loss
  monitor_mode: min
  save_top_k: 1
  limit_train_batches: 0.25
  limit_val_batches: 0.25

diagnostics:
  enabled: false
  log_interval: 50
  profile: false
  gradient_noise_threshold: 4.0
  calibration_bias_threshold: 0.05
  calibration_error_threshold: 0.15

wandb_project: null
wandb_entity: null
wandb_run_name: null
wandb_tags: []
wandb_offline: true
