seed: 42
notes: "consumer gpu friendly masked modelling"

data:
  sqlite_path: data/market.db
  symbol_universe: []
  indicators: {}
  alternative_data: []
  resample_rule: null
  tz_convert: null
  feature_set: null
  target_columns: [close]
  window_size: 384
  horizon: 5
  stride: 4
  normalise: true
  val_fraction: 0.1

model:
  feature_dim: 128
  model_dim: 512
  depth: 12
  heads: 8
  dropout: 0.1
  conv_kernel_size: 7
  conv_dilations: [1, 2, 4, 8, 16, 32]
  horizon: 5
  output_dim: 1
  architecture: omni_mixture
  ff_mult: 4
  ssm_state_dim: 192
  ssm_kernel_size: 12
  coarse_factor: 4
  cross_every: 2
  max_seq_len: 4096
  market_state:
    enabled: false
    embedding_dim: 16
    dropout: 0.05
    include: []

optimizer:
  lr: 0.0003
  weight_decay: 0.01
  betas: [0.9, 0.95]

trainer:
  batch_size: 24
  num_workers: 4
  max_epochs: 25
  gradient_clip_val: 1.0
  accumulate_grad_batches: 1
  accelerator: gpu
  devices: null
  precision: bf16-mixed
  log_every_n_steps: 10
  checkpoint_dir: checkpoints/pretrain_desktop
  monitor_metric: val/pretrain_loss
  monitor_mode: min
  save_top_k: 1
  num_sanity_val_steps: 0
  limit_train_batches: 1.0
  limit_val_batches: 0.5

pretraining:
  mask_prob: 0.25
  mask_value: 0.0
  loss: mse
  objective: masked
  temperature: 0.1
  projection_dim: 256
  augmentations: [jitter, scaling, time_mask]
  jitter_std: 0.02
  scaling_std: 0.1
  time_mask_ratio: 0.2
  time_mask_fill: mean
  monitor_metric: val/pretrain_loss
