seed: 999
notes: "State-space backbone baseline tuned for CPU smoke tests"

data:
  sqlite_path: data/market.db
  symbol_universe: []
  indicators: {}
  alternative_data: []
  resample_rule: null
  tz_convert: null
  feature_set: null
  target_columns: [close]
  window_size: 256
  horizon: 5
  stride: 4
  normalise: true
  val_fraction: 0.2

model:
  feature_dim: 64
  model_dim: 256
  depth: 6
  heads: 4
  dropout: 0.1
  conv_kernel_size: 5
  conv_dilations: [1, 2, 4, 8]
  horizon: 5
  output_dim: 1
  architecture: state_space
  ff_mult: 4
  ssm_state_dim: 128
  ssm_kernel_size: 9
  max_seq_len: 1024
  calibration:
    enabled: false
    quantiles: [0.05, 0.5, 0.95]
    temperature: 1.0
    min_concentration: 0.01
  market_state:
    enabled: false
    embedding_dim: 16
    dropout: 0.0
    include: []

optimizer:
  lr: 0.0004
  weight_decay: 0.0
  betas: [0.9, 0.99]

trainer:
  batch_size: 48
  num_workers: 0
  max_epochs: 8
  gradient_clip_val: 1.0
  accumulate_grad_batches: 1
  accelerator: cpu
  devices: 1
  precision: 32
  matmul_precision: medium
  log_every_n_steps: 20
  checkpoint_dir: checkpoints/benchmarks/baseline
  monitor_metric: val/loss
  monitor_mode: min
  save_top_k: 1
  num_sanity_val_steps: 0
  limit_train_batches: 0.4
  limit_val_batches: 0.4

diagnostics:
  enabled: true
  log_interval: 20
  profile: true
  gradient_noise_threshold: null
  calibration_bias_threshold: null
  calibration_error_threshold: null

wandb_project: null
wandb_entity: null
wandb_run_name: null
wandb_tags: []
wandb_offline: true
